name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bakedbot_ai/bakedbot_ai/requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 bakedbot_ai/

    - name: Run tests
      run: |
        pip install pytest
        pytest bakedbot_ai/tests/

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: your-docker-registry/smokey-api:latest
        # Ensure you have set up secrets for Docker registry authentication